### ISSUE TITLE
erreur plugin spotify

### ISSUE THREAD

**Issue by halimgambit** [Spikharpax/Avatar-Plugin-SonosPlayer#1]
rebonjour stephane,
j ai une erreur sur le plugin sonosplayer

warn: Error while loading plugin: SonosPlayer Cannot find module 'sonos' Error: Cannot find module 'sonos' at Module._resolveFilename (module.js:543:15) at Function.Module._resolveFilename 
(C:\Avatar\resources\electron.asar\common\reset-search-paths.js:35:12) at Function.Module._load (module.js:473:25) at Module.require (module.js:586:17) at require (internal/module.js:11:18) at Object. 
(C:\Avatar\resources\core\plugins\SonosPlayer\SonosPlayer.js:1:199) at Object. 
(C:\Avatar\resources\core\plugins\SonosPlayer\SonosPlayer.js:3531:3) at Module._compile (module.js:642:30) at Object.Module._extensions..js (module.js:653:10) at Module.load (module.js:561:32)
encore une questions stephane
1- le plugin sonoplayer fonctionne uniquement sur les enceintes sonos ou fonctionne aussi sur enceinte du pc?
cordialement

**Comment by Spikharpax** [comment]
Je suis extremement surpris de tes problèmes.
Si tu utilises l'installation du plugins depuis la librairie, je ne sais pas comment c'est possible. L'installation est automatique, fiable et se fait en 2mn...

Comme son nom l'indique, un plugin Sonos est fait pour des enceintes Sonos...
