### ISSUE TITLE
demande de l aide

### ISSUE THREAD

**Issue by halimgambit** [Spikharpax/Avatar-Plugin-SonosPlayer#2]
bonjour stephane,
comme tu m' conseiller j ai retelecharger le plugin sonosplayer depuis la bibliotheque des plugins, effectivelment je n ai aucune erreur, j ai bien l icone sonosplayer sur l'interface du serveur, mais quand j ai clické sur l icone pour la premiere fois, une petite page s est ouverte de spotify  pour renseigner mes identifiant, j ai renseigner mes identifiant, ensuite une petite page s est ouverte spotify : INVALIDE_CLIENT:Invalide rediret URI
est ce que j ai mal renseigner mes identifiant ou j ai pas encore une enceinte sonos?
merci d avance pour ton aide cordialement
ps: j ai bien recuperer  client id et client secret du dashboard spotify

**Comment by Spikharpax** [comment]
Slt,
Je suis vraiment surpris qu'à priori tu ai vraiment installé le plugin sans utiliser la bibliothèque de plugins. Unbon conseil, tu devrais arrêter de passer d'un système (obsolète) à un autre et approfondir tes connaissances sur un seul... si tu vois ce que je veux dire. Ca t'aiderait.

INVALIDE_CLIENT:Invalide rediret URI
Ce message signifie que tu n'as pas mis de callback dans ton projet API Spotify, je me demande même si tu l'as créé :-O
Je me demande même si tu as lu la documentation où tu n'as qu'à suivre pas à pas les copies d'écrans que j'ai passé des heures à faire pour les utilisateurs comme toi.
Je me demande même si tu sais comment ouvrir la documentation.
je ne sais pas quoi dire...

Pour info, je vais fournir une nouvelle version très prochainement qui élimine quelques bugs, Essentiellement sur la partie Spotify,, recherche par titre.
